name: onix_flutter_bloc
description: "Onix Flutter BLoC"
version: 0.0.2
repository: https://github.com/OnixFlutterTeam/onix-flutter-bloc

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  loader_overlay: ^4.0.2+1
  onix_flutter_core_models: ^0.0.1
